### ISSUE TITLE
[Sample Onboard Request] meetings-live-code-interview

### ISSUE THREAD

**Issue by Prithvi-MSFT** [OfficeDev/teams-toolkit-samples#1117]
**Owner:**
Name - Prithvi / GitHub user name - Prithvi-MSFT

**ID:**
meetings-live-code-interview

**Title:**
meetings-live-code-interview

**Description:**
This sample demos live coding in a teams meeting stage using live share SDK. The tab is loaded as side panel which contains various coding questions.

**Tags:**
"JS", "Live Share SDK"

**Time:**
5 mins to run

**Configuration:**
Ready

**Thumbnail:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-live-code-interview/nodejs/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-live-code-interview/nodejs/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
Code in another PR

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-live-code-interview/nodejs

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by JerryYangKai** [comment]
Hi @Prithvi-MSFT, after a quick test, the sample doesn't work in my local machine.
Repro step, download the app, using Teams ToolKit, press F5, in the pop-up browser, click 'install the app'.
Screen shot, in the meeting, cannot add the app, the config page is failed
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/568798dc-5290-457c-8c8f-a6032367860c)

**Comment by prithvi7410** [comment]
@JerryYangKai  - Thanks for reporting the issue. Will check on the sample issue

**Comment by Prithvi-MSFT** [comment]
Hi @JerryYangKai  - The issue is fixed and we have pushed the changes. Could you please verify once
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1109

**Comment by JerryYangKai** [comment]
Hi @Prithvi-MSFT, thanks for your quick reply. 
I afraid I cannot run it in my local environment, I pull the latest changes then when I press F5, the frontend and backend terminal won't work, it will auto close after a few second. The screenshot is in the following:
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/794c63e3-d099-4e93-b244-65999e13e5ba)
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/82bb89aa-eb9a-4d56-87f2-1c7bc264bd66)

**Comment by JerryYangKai** [comment]
@summzhan Sample test passed, please help review the doc part,

**Comment by summzhan** [comment]
README looks good to me.

**Comment by tecton** [comment]
Onboarding PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/1128

**Comment by Prithvi-MSFT** [comment]
@tecton  - By when will it be available in samples list ?

**Comment by tecton** [comment]
> @tecton - By when will it be available in samples list ?

Hi @Prithvi-MSFT, the sample is available in [daily build](https://github.com/OfficeDev/TeamsFx/actions/runs/7698896700) version now. And it's expected to be released in next TTK prerelease version (next month).

**Comment by JerryYangKai** [comment]
Hello @Prithvi-MSFT !
The preview version of teams toolkit has been released, after testing part of sample readme cannot render in VS Code, I created an issue and you can check it.
https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1202

**Comment by summzhan** [comment]
@JerryYangKai  @Prithvi-MSFT , What's the status of this sample? it's seems stucked by weeks.

**Comment by Prithvi-MSFT** [comment]
@JerryYangKai  - Could you please guide me on the repro steps so I can create and test the issue ?

**Comment by JerryYangKai** [comment]
> @JerryYangKai - Could you please guide me on the repro steps so I can create and test the issue?

You can check the issue I created above, it is about the readme rendering, not the code running issue.

**Comment by Prithvi-MSFT** [comment]
@JerryYangKai - In issue its mentioned its in internal preview. Could you please guide how can I test this ? As the readme seem to look correct in repository

**Comment by JerryYangKai** [comment]
> @JerryYangKai - In issue its mentioned its in internal preview. Could you please guide how can I test this ? As the readme seem to look correct in repository

Now this version is released as preview version and can be repro.
Step 1    switch teams toolkit to pre release 5.7.0
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/5e276d23-82ae-4aa6-9a83-dc13ad355be8)

Step 2   find the sample in sample gallery
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/fdfa6f4f-845f-42d8-8bad-fd7d55208776)
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/048a4616-a1d4-46a4-a3ba-b8e5ddd393f5)

Step 3   click the sample to see the readme, and the issue will come out
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/64d211de-8e3c-4bdc-981e-6d032c1eb8a8)
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/1dfda8bc-ded6-4fdc-a49a-a4d83b731e31)

**Comment by Prithvi-MSFT** [comment]
Hi @JerryYangKai ,
I followed the steps mentioned and installed the latest pre-released version of teams toolkit and the images were loading correctly for me.
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/87962396/20c511fb-fe09-4dd5-a182-99b09994d52b)

**Comment by JerryYangKai** [comment]
> Hi @JerryYangKai , I followed the steps mentioned and installed the latest pre-released version of teams toolkit and the images were loading correctly for me. ![image](https://private-user-images.githubusercontent.com/87962396/324322569-d80a6de3-4b17-4349-9594-7b169e7dfab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzQyNTMsIm5iZiI6MTcxMzgzMzk1MywicGF0aCI6Ii84Nzk2MjM5Ni8zMjQzMjI1NjktZDgwYTZkZTMtNGIxNy00MzQ5LTk1OTQtN2IxNjllN2RmYWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAwNTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjNmMjI3OWNlYmM2N2VhYWU4ZjUyNThkNTg2NDNlODI5YWE0NzcxMWVkOWM5YjZkZDRhMzRlNTVlNGM2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._29eCSiaX-Zpf6flhd8O6kzh_weLHsnOkrbHAnzlpFM)

Great!
So this is the issue 2 I mentioned, how about the issue 1
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/53805504/d6dbfdd5-b269-4d78-a7c0-3aaa6e5964bd)
