### ISSUE TITLE
[Sample Onboard Request] Containerized Hello World Tab with Backend

### ISSUE THREAD

**Issue by hund030** [OfficeDev/teams-toolkit-samples#1169]
**Owner:**
@hund030 

**ID:**
hello-world-tab-docker

**Title:**
Containerized Hello World Tab with Backend

**Description:**
A containerized Hello World app of Microsoft Teams Tab app which has a backend service.

**Tags:**
TS
Tab
React
Graph Toolkit
Docker
Single Sign On

**Time:**
5mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/29099060655b8cca0cb4466bd1330243522b15b0/hello-world-tab-docker/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/29099060655b8cca0cb4466bd1330243522b15b0/hello-world-tab-docker/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/TeamsFx-Samples/pull/1167

**(Optional) Minimum Teams Toolkit Version:**
V5.0.0

**(Optional) Maximum Teams Toolkit Version:**
N/A

**Comment by summzhan** [comment]
Reviewed README， please go ahead with testing.

**Comment by summzhan** [comment]
@hund030 , did this sample pass test?

**Comment by hund030** [comment]
@summzhan Not yet. Testers are too busy for prerelease.

**Comment by tecton** [comment]
@hund030 @summzhan This sample has been onboarded.
