### ISSUE TITLE
[Sample Onboard Request] Graph RSC Helper

### ISSUE THREAD

**Issue by xzf0587** [OfficeDev/teams-toolkit-samples#1298]
**Owner:**
xzf0587 Prithvi-MSFT Jegadeesh-MSFT 

**ID:**
graph-rsc-helper

**Title:**
graph-rsc-helper

**Description:**
This sample demonstrates how to use [Resource Specific Consent](https://learn.microsoft.com/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent) to call Graph API in Microsoft teams channel and group chat. You can observe the real API response with the scope installed.

**Tags:**
- TS
- Tab
- RSC Permissions
- Graph

**Time:**
5mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/graph-rsc-helper/nodeJs/Images/Overview.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/graph-rsc-helper/nodeJs/Images/graphrschelper.gif

Sample URL:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc-helper/nodeJs

**Comment by MuyangAmigo** [comment]
Description can be updated as: 

This sample demonstrates how to use [Resource Specific Consent](https://learn.microsoft.com/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent) to call Graph API in teams channel and group chat. You can observe the real API response with the scope installed.

**Comment by xzf0587** [comment]
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1340
The description has been updated.
