### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by xxxpsyduck** [OfficeDev/teams-toolkit-samples#1330]
I'm having this issue when trying to debug sample teams app. It looks like a bug of teamsfx?

![image](https://github.com/user-attachments/assets/a659a240-71d6-4a88-a2a4-a3266373c66e)

**Comment by qinezh** [comment]
@xxxpsyduck which sample app are you using? And could you provide the repro steps?

**Comment by xxxpsyduck** [comment]
@qinezh I follow these steps:

`Team Tookit VSCode extension -> Create New App -> Custom Copilot -> AI Agent -> Build New -> Python -> Azure OpenAI -> ...`

I haven't changed anything in the code yet. Just tried to run debug in Test tool

**Comment by qinezh** [comment]
@xxxpsyduck, I can't repro the issue on my side, would you provide more information to help us troubleshoot it or can you try it again to see whether it still happens?

**Comment by sawanthilips** [comment]
@xxxpsyduck were you able to solve above issue
