### ISSUE TITLE
[Sample Onboard Request] bug report

### ISSUE THREAD

**Issue by daniela2000111** [OfficeDev/teams-toolkit-samples#1346]
**Owner:**
Name and email address/GitHub account of maintainers. We will send email or @you in issues when there's any maintenance work to do in the future.

**ID:**
It should be same with folder name. E.g., "hello-world-sample".

**Title:**
Your sample name. E.g., "Hello World Sample"

**Description:**
One or two sentences to introduce this sample.

**Tags:**
You can give your samples a set of tags so that users can easily locate your sample from a group of samples. Those tags can be:
- the programming languages you used, e.g. "JS", "TS", "C#" etc.
- the Teams app type, e.g. "Tab", "Bot", "Message Extension" etc.
- the highlighted technics you used, e.g. "React", "Azure Function", "Graph Toolkit", "Teams AI SDK", "Live Share SDK" etc.
- the business scenarios of your sample, e.g. "Team Dashboard", "Productivity", "Notification", "Q&A" etc.
You can customize the tag you used for your sample, the recommended number of tags is less than 5.

**Time:**
The estimation time to run the sample. E.g., "5mins to run".

**Configuration:**
Does the sample require additional manual steps to config before it can run? Please fill "Ready for local debug" or "Manual configurations required".

**Thumbnail:**
The file path where you put the thumbnail, typically it's in assets folder(assets/thumbnail.png) but you can put it anywhere you want.
Suggested size of image is 1600x920/800x460 (If you have it with other sizes, please keep same image ratio for other sizes and don't forget to consider the resolution.)

**(Optional) Demo GIF:**
The file path where you put the GIF, typically it's in assets folder(assets/sampleDemo.gif) but you can put it anywhere you want.
Suggested size of image is 1600x920/800x460 (If you have it with other sizes, please keep same image ratio for other sizes and don't forget to consider the resolution.
Your GIF must fit the entire Teams client UI into the image.)

**(Source code in this Repo) Source Code PR:**
The link to pull request that contains sample source codes.

**(Source code NOT in this Repo) Sample URL:**
The URL if your sample code resides in another sample repo. It's better to use a tag instead of a branch for stablility.
E.g., "https://github.com/xxx/xxx/tree/v1.0/xxx".

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by summzhan** [comment]
@daniela2000111 , you will need to provide details of your samples by filling out our template  for us to help you onboard new samples to our sample gallery. Your request is missing information now so please provide them ASAP.
