### ISSUE TITLE
[Sample Onboard Request] Hello World Office Add-in

### ISSUE THREAD

**Issue by hermanwenhe** [OfficeDev/teams-toolkit-samples#1373]
**Owner:**
GitHub id: hermanwenhe
Microsoft alias: hermanwen

**ID:**
hello-world-office-addin

**Title:**
Getting Started with Hello World Office Add-in Sample

**Description:**
A hello world project that contains Office add-in capability

**Tags:** 
Added in the config file of the PR.

**Time:**
5mins to run.

**Configuration:**
Once the host app is ready, it's ready for local debug. It depends on the host app release.
Outlook is already ready. Word Excel Powerpoint might need a few weeks for feature rollout.

**Thumbnail:** assets/thumbnail.png

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/teams-toolkit-samples/pull/1372

**Comment by tecton** [comment]
This sample has been onboarded.
